language: bash
dist: xenial
os:
  - linux
  - osx
  - windows

env:
  - JDK="adopt@1.8.0-232"

cache:
  directories:
    - $HOME/.m2

before_install:
  - curl "https://raw.githubusercontent.com/nidi3/Mavis-CI/master/mavis.sh" --output mavis.sh
  - source mavis.sh
  - install_jdk
  - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar -xf apache-maven-3.6.3-bin.tar.gz
  - ls
  - ln -s apache-maven-3.6.3/bin/mvn /usr/bin/mvn
  - mvn

before_script:
  - before_script

script:
  - script

after_success:
  - bash <(curl -s https://codecov.io/bash)
